name: HelloClaydou
version: '${project.version}'
main: com.intiegames.divinecraft.helloclaydou.HelloClaydou
api-version: '1.20'
commands:
  claydou:
    description: Spawns a new Claydou pig
    usage: /claydou
    permission: helloclaydou.spawn
permissions:
  helloclaydou.spawn:
    description: Allows players to spawn Claydou pigs
    default: op
